### ISSUE TITLE
Replace avatar-large image by my own

### ISSUE THREAD

**Issue by Kevinnko** [baobabKoodaa/blog#1]
Hi Atte,

Thanks a lot for this portfolio starter. 

I'm having trouble trying to put my own picture as avatar-large for the about page. The page is not loading and I get the following error message : 

> Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information

Is it due to the hover effect ? If this is the case, how do you deal with it ? 

Thank you

**Comment by baobabKoodaa** [comment]
Hi, it may be due to the hover effect as you suspected (if for some reason we are unable to generate the tracedsvg image for your original image). Here are some ideas for debugging:

- Make sure it's not a file path issue (e.g. replace my original image without modifying file name or path).
- Make sure it's not related to the specific image you are using (e.g. uncommon file type). You could test this by using my image and making a small change to it and saving as the same file type.
- Sometimes I've seen weird errors disappear by running `gatsby clean` to clear the cache.
- You probably don't care much for the placeholder, so you could just replace my `<re-img>` with a regular `<img>` and get rid of the placeholder altogether.

Let me know how it goes :)

**Comment by Kevinnko** [comment]
Hi, Thanks a lot. It was just a problem of file extension : .jpg instead of jpeg ! And the svg on hover works perfectly.

**Comment by baobabKoodaa** [comment]
Good to hear!
